
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed

  mongo-seed:
    image: mongo:latest
    volumes:
      - /home/popes/Desktop/3ºAno 2ºSemestre/TesteEW/ENGWEB2024-Normal/Ex1/contratos2024.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets/dataset.json --jsonArray
